title:              Xiguang Zheng (郑羲光)
tagline:            
description:        Content-focused template for a blog hosted on GitHub Pages.
url:                http://xz725.github.io

author:
  name:             Xiguang Zheng
  url:              
  email:            xzhen@ieee.org

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
